insert into doggo_timeline (dog_id, title, image, desc_time, time) values (16, 'Ameliorated', 'dogs/default.png', 'scale proactive synergies', '2017-02-26 07:31:57');
insert into doggo_timeline (dog_id, title, image, desc_time, time) values (17, 'strategy', 'dogs/default.png', 'matrix holistic technologies', '2017-01-17 19:52:46');
insert into doggo_timeline (dog_id, title, image, desc_time, time) values (2, 'User-centric', 'dogs/default.png', 'empower enterprise infomediaries', '2017-03-22 11:48:30');
insert into doggo_timeline (dog_id, title, image, desc_time, time) values (16, 'artificial intelligence', 'dogs/default.png', 'enable magnetic markets', '2017-07-25 20:59:17');
insert into doggo_timeline (dog_id, title, image, desc_time, time) values (17, 'Re-contextualized', 'dogs/default.png', 'harness compelling schemas', '2017-08-11 10:29:18');
insert into doggo_timeline (dog_id, title, image, desc_time, time) values (1, 'installation', 'dogs/default.png', 'engage proactive partnerships', '2017-09-22 06:32:55');
insert into doggo_timeline (dog_id, title, image, desc_time, time) values (2, 'Versatile', 'dogs/default.png', 'aggregate next-generation schemas', '2017-09-07 18:40:54');
insert into doggo_timeline (dog_id, title, image, desc_time, time) values (10, 'Triple-buffered', 'dogs/default.png', 'optimize real-time communities', '2017-07-21 18:28:59');
insert into doggo_timeline (dog_id, title, image, desc_time, time) values (10, 'Cloned', 'dogs/default.png', 'deploy enterprise web services', '2017-04-04 23:13:57');
insert into doggo_timeline (dog_id, title, image, desc_time, time) values (7, 'global', 'dogs/default.png', 'visualize visionary metrics', '2016-11-26 10:46:39');
insert into doggo_timeline (dog_id, title, image, desc_time, time) values (6, 'attitude-oriented', 'dogs/default.png', 'extend extensible partnerships', '2017-09-29 08:11:41');
insert into doggo_timeline (dog_id, title, image, desc_time, time) values (2, 'non-volatile', 'dogs/default.png', 'unleash next-generation channels', '2017-08-21 05:13:11');
insert into doggo_timeline (dog_id, title, image, desc_time, time) values (2, 'Monitored', 'dogs/default.png', 'implement one-to-one mindshare', '2017-09-11 07:37:15');
insert into doggo_timeline (dog_id, title, image, desc_time, time) values (5, 'Reduced', 'dogs/default.png', 'reinvent open-source web services', '2017-03-07 09:25:14');
insert into doggo_timeline (dog_id, title, image, desc_time, time) values (7, 'emulation', 'dogs/default.png', 'syndicate revolutionary metrics', '2016-10-05 06:16:17');
insert into doggo_timeline (dog_id, title, image, desc_time, time) values (13, 'project', 'dogs/default.png', 'aggregate e-business metrics', '2016-10-02 00:30:10');
insert into doggo_timeline (dog_id, title, image, desc_time, time) values (13, 'budgetary management', 'dogs/default.png', 'enable strategic paradigms', '2017-08-13 06:06:52');
insert into doggo_timeline (dog_id, title, image, desc_time, time) values (15, 'Synergized', 'dogs/default.png', 'mesh synergistic bandwidth', '2017-05-20 10:18:05');
insert into doggo_timeline (dog_id, title, image, desc_time, time) values (2, 'knowledge user', 'dogs/default.png', 'incentivize strategic infomediaries', '2016-11-21 00:52:56');
insert into doggo_timeline (dog_id, title, image, desc_time, time) values (10, 'pricing structure', 'dogs/default.png', 'syndicate collaborative e-markets', '2017-06-03 10:41:02');